#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input().strip())
    if n % 2 != 0:          # Testing if number is odd
        print("Weird")
    elif 2 <= n <= 5:       # Testing if number is in inclusive range
        print("Not Weird")
    elif 6 <= n <= 20:      # Testing if number is in inclusive range
        print("Weird")
    else:                   # Handling all other numbers 
        print("Not Weird")
